version: '3.8'

services:
  # Dados LAI (parquet + vetores)
  data:
    build:
      context: .
      dockerfile: Dockerfile.data
    container_name: mvp-data
    volumes:
      - data_volume:/data
    restart: unless-stopped
    networks:
      - mvp-network

  # Vector Database - Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: mvp-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - mvp-network

volumes:
  qdrant_storage:
    driver: local
  data_volume:
    driver: local

networks:
  mvp-network:
    driver: bridge